=== Cokosk/Home_Serve/projects/xml-constraint/bookstore.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT bookstore (book+)>
<!ELEMENT book (name, authors, price, core_curriculum, test?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT authors (author+)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT core_curriculum (#PCDATA)>
<!ELEMENT test (#PCDATA)>
<!ATTLIST book id CDATA #REQUIRED>

=== Cokosk/Home_Serve/projects/xml-constraint/bookstoreWithDtdVal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "bookstore.dtd">
<bookstore>
    <book id="a123">
        <name>计算机操作系统</name>
        <authors>
            <author>汤小胖</author>
            <author>王红玲</author>
            <author>姜华林</author>
            <author>汤子瀛</author>
        </authors>
        <price>69.8</price>
        <core_curriculum>是</core_curriculum>
        <test>测试内容</test>
    </book>
    <book id="a124">
        <name>系统功能语言学术核心术语</name>
        <authors>
            <author>Christian M.I.M.Matthiessen</author>
            <author>Kazuhiro Teruya</author>
            <author>林文杰</author>
        </authors>
        <price>37.8</price>
        <core_curriculum>否</core_curriculum>
    </book>
</bookstore>
