=== Cokosk/Home_Serve/projects/xml-constraint/bookstore.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <!-- 定义bookstore元素 -->
    <xs:element name="bookstore">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string"/>
                            <xs:element name="authors">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="author" type="xs:string" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="price" type="xs:decimal"/>
                            <xs:element name="core_curriculum" type="xs:string"/>
                            <xs:element name="test" type="xs:string" minOccurs="0"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>

=== Cokosk/Home_Serve/projects/xml-constraint/bookstoreWithSchemaVal.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookstore xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:noNamespaceSchemaLocation="bookstore.xsd">
    <book id="a123">
        <name>计算机操作系统</name>
        <authors>
            <author>汤小胖</author>
            <author>王红玲</author>
            <author>姜华林</author>
            <author>汤子瀛</author>
        </authors>
        <price>69.8</price>
        <core_curriculum>是</core_curriculum>
        <test>测试内容</test>
    </book>
    <book id="a124">
        <name>系统功能语言学术核心术语</name>
        <authors>
            <author>Christian M.I.M.Matthiessen</author>
            <author>Kazuhiro Teruya</author>
            <author>林文杰</author>
        </authors>
        <price>37.8</price>
        <core_curriculum>否</core_curriculum>
    </book>
</bookstore>
